
export const FETCH_MOVIE_START = 'FETCH_MOVIE_START';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_FAIL = 'FETCH_MOVIE_FAIL';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const SCREEN_RESIZE = 'SCREEN_RESIZE';

